### PR TITLE
fix server side events for remix actions

### LINKED ISSUE #111: Can't use server track in Remix
It seems the track function uses the "use-server" package and that fails to detect when running in a remix action apparently.

I've got a `analytics.server.ts` file which exports the track function from this package, ive added a "use server" line at the top but I still get:

```
Error: This module cannot be imported from a Client Component module. It should only be used from a Server Component.
```

Any ideas what I could be doing wrong?

p.s also had to add @vercel/analytics to remix's serverDependenciesToBundle config

### PR DESCRIPTION
**Pull request by tobiaslins**
- Fixes #111 
- Add Remix example project

### CODE REVIEW

File: packages/web/src/server/index.ts [hunk 1]
```diff
@@ -32,24 +31,35 @@ interface RequestContext {
...
 
 export async function track(
   eventName: string,
   properties?: Record<string, AllowedPropertyValues>,
   context?: Context
 ): Promise<void> {
+  if (typeof window !== 'undefined') {
+    if (!isProduction()) {
+      throw new Error(
+        `${logPrefix} It seems like you imported the \`track\` function from \`@vercel/web-analytics/server\` in a browser environment. This function is only meant to be used in a serverless environment.`
```
Comment (chriswdmr) [inline packages/web/src/server/index.ts:44]: I believe edge is also working, maybe we should only mention `server` instead of `serverless`.

```suggestion
        `${logPrefix} It seems like you imported the \`track\` function from \`@vercel/web-analytics/server\` in a browser environment. This function is only meant to be used in a server environment.`
```

**Review by chriswdmr — APPROVED** [review]
Thanks for adding the example app 🙌
